### ISSUE TITLE
[FEAT] Support CRUD controller 

### ISSUE THREAD

**Issue by Romakita** [tsedio/tsed#1015]
## Information

As a developer I want to create a CRUD controller which follow the Rest API convention.

## Example
```typescript
import {CrudController, CrudService} from "@tsed/crud";

export class UserService implement CrudService<User> {
  
}

@CrudController({
   path: '/users',
   model: User
})
export class UsersCtrl {
   constructor(protected service: UserService) {}
}
```

## CrudService interface

To be defined

## Acceptance criteria

- [ ] A new package is available on NPM `@tsed/crud`.
- [ ] OpenSpec is correctly generated.
- [ ] Validation is correctly executed based on the given Model.
- [ ] Base methods can be overriden.

**Comment by Romakita** [comment]
Groups and RequiredGroups allow now this usage. We need a Partial decorator to finish this story.

**Comment by raduconst06** [comment]
Hi. Could you describe a bit how to use Groups / RequiredGroups to allow this usage, please?

**Comment by Romakita** [comment]
@petruconst  It's described on the official doc: https://tsed.io/docs/model.html#requiredgroups
