### ISSUE TITLE
 Is it possible to get json object decribing all the routes and their respective methods in one of the server hooks?

### ISSUE THREAD

**Issue by shivanshtalwar0** [tsedio/tsed#1160]
Just like info regarding routes and methods are spit out of server when it is started up.

┌────────────────┬──────────────────────────┬───────────────────────────────────┐
│ Method         │ Endpoint                 │ Class method                      │
│────────────────│──────────────────────────│───────────────────────────────────│
│ GET            │ /rest/auth/health        │ Auth.healthCheck()                │
│────────────────│──────────────────────────│───────────────────────────────────│
│ POST           │ /rest/auth/login         │ Auth.logIn()                      │
│────────────────│──────────────────────────│───────────────────────────────────│
│ POST           │ /rest/auth/resetPassword │ Auth.resetPassword()              │
│────────────────│──────────────────────────│───────────────────────────────────│
│ GET            │ /rest/auth/verify/:token │ Auth.verifyAccount()              │
│────────────────│──────────────────────────│───────────────────────────────────│
│ POST           │ /rest/auth/register      │ Auth.register()                   │
│────────────────│──────────────────────────│───────────────────────────────────│
│ POST           │ /rest/auth/google        │ Auth.googleAuth()                 │
│────────────────│──────────────────────────│───────────────────────────────────│
│ GET            │ /rest/auth/reset/:token  │ Auth.validateResetPasswordToken() │
│────────────────│──────────────────────────│───────────────────────────────────│
│ POST           │ /rest/auth/reset/:token  │ Auth.applyResetPasswordToken()    │
│────────────────│──────────────────────────│───────────────────────────────────│
│ GET            │ /rest/rbac/role          │ Auth.getRoles()                   │
│────────────────│──────────────────────────│───────────────────────────────────│
│ POST           │ /rest/rbac/role          │ Auth.createRoles()

**Comment by Romakita** [comment]
Hello @shivanshtalwar0,

```typescript
import {Platform} from "@tsed/common";

@Configuration()
export class Server { 
  @Inject()
  platform: Platform;

  $onReady(){
    const routes = this.platform.getRoutes()
  } 
}
```
You can also build your own json by using platform API (if you want more details). See the swagger service example:

https://github.com/TypedProject/tsed/blob/production/packages/swagger/src/services/SwaggerService.ts#L43

See you
Romain

**Comment by shivanshtalwar0** [comment]
Wow thank you so much! 😄

**Comment by shivanshtalwar0** [comment]
@Romakita is it removed in v7?

**Comment by Romakita** [comment]
Yes it’s replaced by `this.platform.getLayers()`.
It’s exactly the same object. 

You can find here how a layer is mapped to display logs:
https://github.com/tsedio/tsed/blob/0f675583d6093385cbecd568928ee6458131f131/packages/platform/common/src/builder/PlatformBuilder.ts#L354

see you
