### ISSUE TITLE
Websocket supertest support

### ISSUE THREAD

**Issue by angusmunro** [tsedio/tsed#1397]
## Informations
**Is your feature request related to a problem? Please describe.**
TSED has extremely good support for supertests, given the decorators for websockets it would also make sense for it to support super tests for websockets. Someone has created a package adding the supertest support for this (https://www.npmjs.com/package/superwstest), and it would offer really good value to the ecosystem to have support for this package in tsed.

**Describe the solution you'd like**
I'd like to see the ability to leverage the functionality from (https://www.npmjs.com/package/superwstest) using the server object from tsed.

**Describe alternatives you've considered**
Currently we are running a live instance of our server and running test code against it.

## Acceptance criteria

- [x] Can mount a server with socket endpoint
- [x] Can send data to the socket endpoint and run asserts against the response
- [x] Can teardown the connection
- [x] Documented basic example, similar to what is available at https://tsed.io/docs/testing.html#test-your-rest-api

**Comment by Romakita** [comment]
Hello @angusmunro 

thanks for the proposition but this tools is to test WebSocket and not a Socket.io server :(
I'll try to give you an equivalent of PlatformTest to testing SocketIO server soon.

See you
Romain

**Comment by angusmunro** [comment]
Hey Romakita,

Thanks again for all your hard work on this project. You are correct in understanding what I'm looking for!

I've been working to migrate all our APIS from tsed v4 and v5 to v6 and this is the last piece of the puzzle I need to make all our testing much faster, efficient and dev friendly!

**Comment by Romakita** [comment]
https://github.com/tsedio/tsed/pull/1427
