### ISSUE TITLE
[BUG] Can not run npm run build

### ISSUE THREAD

**Issue by thanhchuongbmd** [tsedio/tsed#1417]
## Information

- **Version:** 5.x
- Packages: 
 "@tsed/common": "5.67.0",
    "@tsed/core": "5.67.0",
    "@tsed/multipartfiles": "5.67.0",
    "@tsed/swagger": "5.67.0",
    "@tsed/typeorm": "5.67.0",
    "@tsed/platform-express": "5.67.0",
    "@tsed/exceptions": "5.67.0",
    "@tsed/di": "5.67.0",

I run "npm run build", then it not work with error typescript. See image below

<img width="992" alt="Screen Shot 2021-05-30 at 9 05 45 PM" src="https://user-images.githubusercontent.com/67777599/120107321-d77eef80-c18a-11eb-805b-edaf4ae496c7.png">

**Comment by Romakita** [comment]
Try to upgrade your typescript please

**Comment by thanhchuongbmd** [comment]
> Try to upgrade your typescript version please

Thank you, it work ok!
