### ISSUE TITLE
Invalid null check for PlatformContext Request

### ISSUE THREAD

**Issue by JarekToro** [tsedio/tsed#1422]
https://github.com/tsedio/tsed/blob/653299d9cb40a8e702b7e520a453066db82225e7/packages/common/src/platform/domain/PlatformContext.ts#L96

Maybe this is intended.

Checking for response to set the request seems incorrect.

> Note: I have not experienced any issue with this.

> I just came across this when investigating how the platform Context works. Figured I'd share. Feel free to close.

**Comment by Romakita** [comment]
Exact ^^ you can create small PR to fix that ;)

**Comment by JarekToro** [comment]
@Romakita 
I realized I merged into master. Should I have merged into production instead?

**Comment by Romakita** [comment]
Yes it’s on production you have to create pull request xD
