### ISSUE TITLE
[FEAT] Mongoose Discriminators

### ISSUE THREAD

**Issue by c1moore** [tsedio/tsed#809]
## Information
Mongoose supports "inheritance" through a feature call ["discriminators"](https://mongoosejs.com/docs/discriminators.html).  It would be great if Ts.ED could support discriminators with its mongoose integration.  I searched the repo for "discriminator" so I assume this feature doesn't exist yet.

**Describe the solution you'd like**

```typescript
import {
  Property, Required, Pattern, PropertyType,
} from '@tsed/common';
import { Model, ObjectID, Unique } from '@tsed/mongoose';

@Model()
export abstract class Device {
  @ObjectID()
  id: string;

  @Unique()
  @Required()
  @Pattern(/^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$/)
  ipAddress: string;

  @DiscriminatorKey()
  type: string;
}

@Model({
  parent: Device, // can be inferered implicitly because MyDevice inherit from Device with the anscestorOf() function
})
export class MyDevice extends Device {
  @Required()
  status: string;
}
```

**Describe alternatives you've considered**
I've also looked into whether or not you can just specify the underlying collection that should be used.  This would effectively have the same result, but without the builtin functionality.

## Technical solution

We can use the `@VirtualRef` decorator to create the `@DiscriminatorKey` (see https://github.com/TypedProject/tsed/blob/production/packages/mongoose/src/decorators/virtualRef.ts)

```typescript
import {PropertyFn} from "@tsed/common";
import {MONGOOSE_SCHEMA_OPTIONS} from "../constants"; // this constant doesn't exists we need to create it

// This code is equivalent to the official mongoose example
// const options = {discriminatorKey: 'kind'};
// const eventSchema = new mongoose.Schema({time: Date}, options);

export function DiscriminatorKey(): PropertyDecorator {
  return PropertyFn((entity) => {
      entity.store.merge(MONGOOSE_SCHEMA_OPTIONS, {
        discriminatorKey: entity.propertyKey
      }) 
  })
}
```

Then we need to apply this options when the schema is create by Ts.ED.
See createSchema method [here](https://github.com/TypedProject/tsed/blob/09105fca3bd7e7e75c725279cf604755c73e7a47/packages/mongoose/src/utils/createSchema.ts#L44)

```typescript
export function createSchema(target: Type<any>, options: MongooseSchemaOptions = {}): mongoose.Schema {
  // Exercise: Merge schemaOptions by using the store: Store.from(target).get(MONGOOSE_SCHEMA_OPTIONS)
  // Don't forget, get(MONGOOSE_SCHEMA_OPTIONS) can return undefined! 
  options.schemaOptions = // ... write code
  // END

  const schema = setUpSchema(buildMongooseSchema(target), options.schemaOptions);

  schemaOptions(target, options);
  setUpTarget(target);
  schema.loadClass(target);

  return schema;
}
```
The last step is to link the parent schema with the child schema. It's correspond to the part of code described by mongoose:

```typescript
const ClickedLinkEvent = Event.discriminator('ClickedLink',
  new mongoose.Schema({url: String}, options));
```

In the @Model decorator we can check if the parent class has a discrimator key in create the link between parent and child:
https://github.com/TypedProject/tsed/blob/09105fca3bd7e7e75c725279cf604755c73e7a47/packages/mongoose/src/utils/createModel.ts#L16

```typescript
export function createModel<T>(
  target: any,
  schema: mongoose.Schema,
  name: string = nameOf(target),
  collection?: string,
  skipInit?: boolean,
  connection?: Connection
) {
  // if ancestor has a discriminatorKey we need to link model with anscestor schema
  const anscestor = anscestorOf(target).find((ancestor) => { 
      // retrieve options
      const options = Store.from(target).get(MONGOOSE_SCHEMA_OPTIONS) || {}
      return options.discriminatorKey
  }}

  if (ancestor) {
     // we can get the model by using store (but you have to set the parent model in the store ;) see exercise 2 )
     const parentModel = Store.from(ancestor).get(MONGOOSE_MODEL);  // MONGOOSE_MODEL is a new constant
 
     // Excercise 1: Link parent model with the schema of the current class (target) and return the generated model
    return discriminatorModel
  }

  // Exercise 2:  refactor this code to store model with the new MONGOOSE_MODEL
  if (connection) {
    return connection.model(name, schema, collection);
  }

  return mongoose.model(name, schema, collection, skipInit);  
}
```
> Don't hesitate to split you code in small function ;)

## Acceptance criteria

- [ ] Discriminator support
- [ ] Unit test are correctly implemented
- [ ] mongoose.md documentation is up-to-date

**Comment by Romakita** [comment]
Hello @c1moore 
I totally forgot this issue. I think it could be added to the @tsed/mongoose package by taking as example the `@Ref` decorator

**Comment by Romakita** [comment]
PR by @ochrstn #1430
