### ISSUE TITLE
[DOC] Add a complete tutorial to create an application from scratch

### ISSUE THREAD

**Issue by Romakita** [tsedio/tsed#851]
This issue is open for any contributors.

The goal is to improve the getting-started by adding a complete tutorial to create an Ts.ED application from scratch.
We can get a Todo List application example to explain the different possibility of our Framework.

**Comment by flexwie** [comment]
I could give this a try.
Don't know if I can cover the more advanced stuff tho as I am just getting used to working with this framework...

**Comment by Markkos89** [comment]
yes I can lift a hand on this too. Im starting with the framework because of my work and im loving it. let me know if I can help @flexwie regards

**Comment by flexwie** [comment]
@Markkos89 I just shot you a mail regarding this!
@Romakita Can you send an invite to our Slack?

**Comment by Romakita** [comment]
Yes sure: https://join.slack.com/t/tsed-framework/shared_invite/zt-o60j36v7-IuRWDBsfTU_jiXT4HbNHWA
